version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-browsers
      
    working_directory: ~/aqapython
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt-add-repository ppa:qameta/allure
            sudo apt-get update
            sudo apt-get install allure


      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --alluredir=/tmp/test-reports -v -l

      - store_artifacts:
          path: /tmp/test-reports
          destination: test-reports

      - store_artifacts:
          path: target/screenshots
