version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch-node-browsers
      
    working_directory: ~/aqapython
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: install allure
          command: |
            curl -o allure-2.7.0.zip -Ls https://bintray.com/qameta/generic/download_file?file_path=io%2Fqameta%2Fallure%2Fallure%2F2.7.0%2Fallure-2.7.0.zip
            unzip allure-2.7.0.zip
            chmod -R 777 ./allure-2.7.0/bin/

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --alluredir=/tmp/test-reports -v -l

      - run:
          name: generate report
          command: |
            ./allure-2.7.0/bin/allure generate -c /tmp/test-reports -o /tmp/my_allure_report
          when: always

      - store_artifacts:
          path: /tmp/my_allure_report
          destination: my_allure_report
