version: 2
jobs:
  build:
    docker:
      image: circleci/python:3.7.0-browsers
      
    working_directory: ~/aqapython
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -n 4 --dist=loadscope --reruns 2 -v -l

      - store_artifacts:
          path: test-reports
          destination: test-reports
          